#!/bin/bash

# This script contains the variables which are used during CI on VM instances.
# Copy/rename this file in case you want to change the default variables.

# The URL to check if the VM is in maintenance
maintenanceURL="http://foo.bar/maintenance/linux"
# The URL with the runCI blob
runCIURL="https://raw.githubusercontent.com/CCExtractor/sample-platform/master/install/ci-vm/ci-linux/ci/runCI"
# Directory where the test suite is located
suiteDstDir="/repository"
# Shell script to launch the test suite
tester="/repository/ccextractortester"
# Location of the samples
sampleFolder="/repository/TestFiles"
# Location of the result files
resultFolder="/repository/TestResults"
# Testfile location
testFile="/repository/vm_data/ci-tests/TestAll.xml"
# The folder that will be used to store the results in
reportFolder="/repository/reports"
# The folder that will be used to temporarily store the result files in
tempFolder="/repository/TempFiles"
# Directory where ccextractor executable is located
dstDir="/repository/vm_data/unsafe-ccextractor"
