#!/bin/bash

# This script contains the variables which we don't want to post on GitHub
# Copy/rename this to variables, and fill this in.

# File that contains the URL to report to
reportURLFile="/path/to/token/file"
# Directory that contains the sources of the version to test
srcDir="/path/to/ccextractor/repository"
# Directory to copy the files to
dstDir="/new/path/to/ccextractor/repository"
# Directory where the test suite is located
suiteSrcDir="/path/to/test/suite"
# Directory where the test suite is located
suiteDstDir="/path/to/test/suite"
# Shell script to launch the test suite
tester="./ccextractortester"
# Location of the samples
sampleFolder="/path/to/test/files"
# Location of the result files
resultFolder="/path/to/result/files"
# Testfile location
testFile="/path/to/testfile.xml"
# The folder that will be used to store the results in
reportFolder="/path/to/folder/"
# The folder that will be used to temporarily store the result files in
tempFolder="/path/to/temp/folder/"
