"""initial

Revision ID: 651b01bb8bec
Revises: 
Create Date: 2018-12-03 23:42:47.157230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651b01bb8bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customized_test_ibfk_2', 'customized_test', type_='foreignkey')
    op.create_foreign_key(None, 'customized_test', 'regression_test', ['regression_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customized_test', type_='foreignkey')
    op.create_foreign_key('customized_test_ibfk_2', 'customized_test', 'regression_test', ['regression_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
