"""empty message

Revision ID: 45faecb8d4e1
Revises: 2e0d2e02a721
Create Date: 2022-09-28 04:49:33.517483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45faecb8d4e1'
down_revision = '2e0d2e02a721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcp_instance',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('timestamp_prep_finished', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('name'),
    mysql_engine='InnoDB'
    )
    op.drop_table('kvm')
    op.alter_column('test_progress', 'status',
               existing_type=mysql.ENUM('completed', 'testing', 'preparation', 'canceled'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_progress', 'status',
               existing_type=mysql.ENUM('completed', 'testing', 'preparation', 'canceled'),
               nullable=True)
    op.create_table('kvm',
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('test_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('timestamp_prep_finished', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], name='kvm_ibfk_1', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('gcp_instance')
    # ### end Alembic commands ###
