"""empty message

Revision ID: 6b335fbd58ab
Revises: 
Create Date: 2019-06-13 16:15:48.053440

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6b335fbd58ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_engine='InnoDB'
    )
    op.create_table('ccextractor_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('released', sa.Date(), nullable=True),
    sa.Column('commit', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit'),
    sa.UniqueConstraint('released'),
    sa.UniqueConstraint('version'),
    mysql_engine='InnoDB'
    )
    op.create_table('extension_forbidden',
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('extension'),
    mysql_engine='InnoDB'
    )
    op.create_table('fork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github'),
    mysql_engine='InnoDB'
    )
    op.create_table('general_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    mysql_engine='InnoDB'
    )
    op.create_table('maintenance_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', database.DeclEnumType('linux', 'windows'), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('mimetype_forbidden',
    sa.Column('mimetype', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('mimetype'),
    mysql_engine='InnoDB'
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=128), nullable=True),
    sa.Column('extension', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha'),
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('github_token', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', database.DeclEnumType('admin', 'user', 'contributor', 'tester'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    mysql_engine='InnoDB'
    )
    op.create_table('ftpd',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=False),
    sa.Column('status', database.DeclEnumType('0', '1'), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('dir', sa.String(length=128), nullable=False),
    sa.Column('ip_access', sa.String(length=16), nullable=False),
    sa.Column('quota_files', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('regression_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('input_type', database.DeclEnumType('file', 'stdin', 'udp'), nullable=True),
    sa.Column('output_type', database.DeclEnumType('file', 'null', 'tcp', 'cea708', 'multiprogram', 'stdout', 'report'), nullable=True),
    sa.Column('expected_rc', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('sample_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('extension', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('sample_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', database.DeclEnumType('linux', 'windows'), nullable=False),
    sa.Column('test_type', database.DeclEnumType('commit', 'pr'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('fork_id', sa.Integer(), nullable=True),
    sa.Column('branch', sa.Text(), nullable=False),
    sa.Column('commit', sa.String(length=64), nullable=False),
    sa.Column('pr_nr', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fork_id'], ['fork.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    mysql_engine='InnoDB'
    )
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('platform', database.DeclEnumType('linux', 'windows', 'mac', 'bsd'), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['ccextractor_version.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('upload_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('upload_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=128), nullable=True),
    sa.Column('extension', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha'),
    mysql_engine='InnoDB'
    )
    op.create_table('customized_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('regression_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regression_id'], ['regression_test.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('kvm',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('name'),
    mysql_engine='InnoDB'
    )
    op.create_table('regression_test_category',
    sa.Column('regression_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regression_id'], ['regression_test.id'], onupdate='CASCADE', ondelete='RESTRICT')
    )
    op.create_table('regression_test_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regression_id', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Text(), nullable=True),
    sa.Column('correct_extension', sa.String(length=64), nullable=False),
    sa.Column('expected_filename', sa.Text(), nullable=True),
    sa.Column('ignore', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['regression_id'], ['regression_test.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('test_fork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('test_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('status', database.DeclEnumType('preparation', 'building', 'testing', 'completed', 'canceled'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('test_result',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('regression_test_id', sa.Integer(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('expected_rc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regression_test_id'], ['regression_test.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', 'regression_test_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('test_result_file',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('regression_test_id', sa.Integer(), nullable=False),
    sa.Column('regression_test_output_id', sa.Integer(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('got', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['regression_test_id'], ['regression_test.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regression_test_output_id'], ['regression_test_output.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', 'regression_test_id', 'regression_test_output_id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_result_file')
    op.drop_table('test_result')
    op.drop_table('test_progress')
    op.drop_table('test_fork')
    op.drop_table('regression_test_output')
    op.drop_table('regression_test_category')
    op.drop_table('kvm')
    op.drop_table('customized_test')
    op.drop_table('upload_queue')
    op.drop_table('upload_log')
    op.drop_table('upload')
    op.drop_table('test')
    op.drop_table('sample_issue')
    op.drop_table('sample_extra')
    op.drop_table('regression_test')
    op.drop_table('ftpd')
    op.drop_table('user')
    op.drop_table('sample')
    op.drop_table('mimetype_forbidden')
    op.drop_table('maintenance_mode')
    op.drop_table('general_data')
    op.drop_table('fork')
    op.drop_table('extension_forbidden')
    op.drop_table('ccextractor_version')
    op.drop_table('category')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###
