"""Add pending_deletion table for VM deletion tracking

Revision ID: c8f3a2b1d4e5
Revises: 7793881905c5
Create Date: 2025-12-30 12:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c8f3a2b1d4e5'
down_revision = '7793881905c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_deletion',
        sa.Column('vm_name', sa.String(length=64), nullable=False),
        sa.Column('operation_name', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('vm_name'),
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_deletion')
    # ### end Alembic commands ###
