"""Add test progress tracking fields

Revision ID: c8f3d9a4b2e1
Revises: b3ed927671bd
Create Date: 2025-12-27 23:05:22

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c8f3d9a4b2e1'
down_revision = 'b3ed927671bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_test', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_tests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_progress', schema=None) as batch_op:
        batch_op.drop_column('total_tests')
        batch_op.drop_column('current_test')
    # ### end Alembic commands ###
