"""Add never_worked column to regression_test table

Revision ID: d9f4e5a6b7c8
Revises: c8f3a2b1d4e5
Create Date: 2026-03-20 23:25:21.411651000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd9f4e5a6b7c8'
down_revision = 'c8f3a2b1d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regression_test', sa.Column('never_worked', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regression_test', 'never_worked')
    # ### end Alembic commands ###
